config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  get 'users/my_portfolio'
  devise_for :users
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  get "my_portfolio", to: "users#my_portfolio"
  get "search_stock", to: "stocks#search"

  get "my_friends", to: "users#my_friends"
  get "search_friend", to: "users#search"
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://cloud.iexapis.com/v1'
    )
    begin
      new(ticker: ticker, name: client.company(ticker).company_name, price: client.price(ticker))
    rescue => exception
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker)
    stock = Stock.where(ticker: ticker).first
    return false unless stock
      stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker)
    stocks.count < 10 && !stock_already_tracked?(ticker)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = matches("first_name", param) + matches("last_name", param) + matches("email", param)
    return nil unless to_send_back
    to_send_back.uniq
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id}
  end

  def is_friend_with?(friend_id)
    self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following user"
    else
      flash[:alert] = "Could not follow user"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash.now[:notice] = "Stop following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    ticker = params[:stock]
    if ticker.present? && ticker.length > 0
      @stock = Stock.new_lookup(ticker)
      if @stock

      else
        flash.now[:alert] = "Stock " + ticker + " not found"
      end
    else
      flash.now[:notice] = "Please enter a symbol"
    end

    respond_to do |format|
      format.js { render partial: "users/result"}
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    if !current_user.can_track_stock?(params[:ticker])
      flash.now[:notice] = "Cannot track stock #{stock.ticker}"
      redirect_to my_portfolio_path
    end
    stock = Stock.where(ticker: params[:ticker]).first
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      if stock.present?
        stock.save
      else
        render html: "Ticker not found"
      end
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash.now[:notice] = "Stock #{stock.ticker} added to portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user: current_user, stock: stock).first
    user_stock.destroy
    flash.now[:notice] = "Stock #{stock.ticker} removed"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def search
    param = params[:friend]
    if param.present?
      @friends = User.search(param)
      @friends = current_user.except_current_user(@friends)
    end
    respond_to do |format|
      format.js { render partial: "friends/result"}
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-sm-9">
    <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Email</th>
        <th scope="col">Full Name</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td scope="row"><%= friend.email %></td>
          <td><%= friend.full_name %></td>
          <td>
            <%= link_to "View Profile", user_path(friend), class: "btn btn-xs btn-success" %>
            <%= link_to "Stop watching", friendship_path(friend), method: :delete, class: "btn btn-xs btn-warning" %>
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/friends/_result.html.erb
<div class="result-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends.length > 0 %>
<div class="card card-header result-block">
  <table class="table table-condense">
    <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td> <strong>Email:</strong> <%= friend.email %> <td>
        <td> <strong>Full Name:</strong> <%= friend.full_name %> </td>
        <td> <strong>Profile: </strong> <%= link_to "View Profile", user_path(friend),
                                            class: "btn btn-success" %> </td>
        <td>
          <% if current_user.is_friend_with?(friend.id) %>
            <span class="badge bg-secondary"> You are already friend</span>
          <% else %>
            <%= link_to "Follow", friendships_path(friend: friend), method: :post, class: "btn btn-xs btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% else %>
No friend found
<% end %>

app/views/friends/_result.js.erb
document.getElementById("result").innerHTML = "<%= j render partial: 'friends/result', formats: :html %>";

app/views/friendship/create.html.erb
<h1>Friendship#create</h1>
<p>Find me in app/views/friendship/create.html.erb</p>

app/views/friendship/destroy.html.erb
<h1>Friendship#destroy</h1>
<p>Find me in app/views/friendship/destroy.html.erb</p>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<%if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Finance Tracker",  root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if current_user %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
          <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Friends", my_friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon "edit" %> Edit Profile
              <% end %>
            </li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item user-name">
          <%= fa_icon "user" %>
          <%= current_user.full_name %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-xs", method: :delete %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-sm-9">
    <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tracked_stocks.each do |stock| %>
        <tr>
          <td scope="row"><%= stock.ticker %></td>
          <td><%= stock.name %></td>
          <td><%= stock.price %></td>
          <td>
            <% if current_user.id == @user.id %>
              <%= link_to "Remove", user_stock_path(stock), method: :delete, class: "btn btn-xs btn-warning" %>
            <% else %>
              <% if current_user.can_track_stock?(stock.ticker) %>
                <%= link_to "Add to portfolio",
                          user_stocks_path(user: current_user, ticker: stock.ticker),
                          class: "btn btn-success btn-xs", method: :post %>
              <% else %>
                <span class="badge badge-secondary">
                  You are already tracking the stock
                </span>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/users/_result.html.erb
<div class="result-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
<div class="card card-header result-block">
  <strong>Symbol:</strong> <%= @stock.ticker %>
  <strong>Name:</strong> <%= @stock.name %>
  <strong>Price:</strong> <%= @stock.price %>
  <% if current_user.can_track_stock?(@stock.ticker) %>
    <%= link_to "Add to portfolio",
              user_stocks_path(user: current_user, ticker: @stock.ticker),
              class: "btn btn-success btn-xs", method: :post %>
  <% else %>
    <span class="badge badge-secondary">
      You are already tracking the stock
    </span>
  <% end %>
</div>
<% end %>

app/views/users/_result.js.erb
document.getElementById("result").innerHTML = "<%= j render partial: 'users/result', formats: :html %>";

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9">
          <%= text_field_tag :friend, params[:friend], placeholder: "Friend name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon "search" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="result">

</div>

<% if @friends %>
  <%= render "friends/list" %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9">
          <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon "search" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="result">

</div>

<%= render "stocks/list" %>

app/views/users/show.html.erb
<h2> User </h2>

Name: <%= @user.full_name %>
Email: <%= @user.email %>
<% if current_user.is_friend_with?(@user.id) %>
<span class="badge bg-secondary"> You are already friend</span>
<% else %>
<%= link_to "Follow", friendships_path(friend: @user), method: :post, class: "btn btn-xs btn-success" %>
<% end %>

<%= render "stocks/list" %>

app/views/welcome/index.html.erb
<h1>Welcome to the FinanceTracker app</h1>
<p>Find me in app/views/welcome/index.html.erb</p>


<%= link_to 'Sign out', destroy_user_session_path, data: {turbo_method: :delete} %>